CREATE TABLE Books (
 BookID INT PRIMARY KEY IDENTITY,
 Title NVARCHAR(255),
 Author NVARCHAR(255),
 Category NVARCHAR(255),
 Price DECIMAL(10,2),
 Description NVARCHAR(MAX),
 Stock INT
);

CREATE TABLE Users(
 UserID INT PRIMARY KEY IDENTITY,
 Username NVARCHAR(255) UNIQUE,
 Password NVARCHAR(255),
 Email NVARCHAR(255),
 Role NVARCHAR(50) DEFAULT 'User'
);

CREATE TABLE Orders (
    OrderID INT PRIMARY KEY IDENTITY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    OrderDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE OrderDetails (
    OrderDetailID INT PRIMARY KEY IDENTITY,
    OrderID INT FOREIGN KEY REFERENCES Orders(OrderID),
    BookID INT FOREIGN KEY REFERENCES Books(BookID),
    Quantity INT,
    Price DECIMAL(10, 2)
);